import type { ThemeConfig } from 'antd'

export const adminTheme: ThemeConfig = {
  token: {
    colorPrimary:         '#0A2540',
    colorPrimaryHover:    '#0D3361',
    colorBgContainer:     '#FFFFFF',
    colorBgLayout:        '#F0F2F5',
    colorText:            '#111827',
    colorTextSecondary:   '#6B7280',
    colorBorder:          '#E5E7EB',
    colorBorderSecondary: '#F3F4F6',
    colorSuccess:         '#059669',
    colorWarning:         '#D97706',
    colorError:           '#DC2626',
    colorInfo:            '#2563EB',
    colorFillAlter:       '#F9FAFB',
    colorBgElevated:      '#FFFFFF',
    fontFamily:           "'Inter', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif",
    fontSize:             14,
    fontSizeLG:           16,
    borderRadius:         6,
    borderRadiusLG:       8,
    borderRadiusSM:       4,
    controlHeight:        36,
    lineHeight:           1.5715,
    boxShadow:            '0 1px 3px rgba(0,0,0,0.08), 0 0 0 1px rgba(0,0,0,0.03)',
    boxShadowSecondary:   '0 4px 12px rgba(0,0,0,0.10)',
    motionDurationMid:    '0.2s',
    motionDurationSlow:   '0.3s',
  },
  components: {
    Layout: {
      siderBg:      '#FFFFFF',
      headerBg:     '#FFFFFF',
      headerHeight: 52,
      triggerBg:    '#F5F6F8',
      triggerColor: '#374151',
    },
    Menu: {
      itemBg:            '#FFFFFF',
      itemHoverBg:       '#F5F7FF',
      itemSelectedBg:    '#EEF2FF',
      itemColor:         '#374151',
      itemHoverColor:    '#1e3a5f',
      itemSelectedColor: '#0A2540',
      iconSize:          16,
      itemMarginInline:  8,
      itemBorderRadius:  6,
    },
    Table: {
      headerBg:          '#F9FAFB',
      headerColor:       '#374151',
      rowHoverBg:        '#F5F7FF',
      borderColor:       '#E5E7EB',
      cellPaddingBlock:  12,
      cellPaddingInline: 16,
    },
    Button: {
      primaryColor:       '#FFFFFF',
      defaultBorderColor: '#E5E7EB',
    },
    Drawer: {
      footerPaddingBlock:  16,
      footerPaddingInline: 24,
    },
    Card: {
      paddingLG:    20,
      headerHeight: 48,
    },
    Modal: {
      paddingContentHorizontalLG: 24,
    },
    Tabs: {
      itemColor:         '#6B7280',
      itemHoverColor:    '#0A2540',
      itemSelectedColor: '#0A2540',
      inkBarColor:       '#0A2540',
    },
    Descriptions: {
      labelBg: '#F9FAFB',
    },
  },
}
